### ISSUE TITLE
how to configure if used in conjunction with serverless plugin?

### ISSUE THREAD

**Issue by aterreno** [iopipe/iopipe-js-logger#17]
We have iopipe configured with the plugin on serverless.yml
```
plugins:
  - serverless-plugin-iopipe
``` 
I've then changed my package.json to configure the plugins

```
  "iopipe": {
    "token": "SECRET",
    "plugins": [
      "@iopipe/trace",
      "@iopipe/profiler",
      "@iopipe/logger"
    ]
  }
```
On iopipe I can tell that it's all good, I can see the lambda, I can see `The trace plugin was enabled for this invocation, but no trace measurements were created.` but no logs. 

What else do I need to configure? 

thanks

**Comment by aterreno** [comment]
thanks @kolanos 
the generated code, using  core==1.13.0 now looks like this:

```
require('@iopipe/trace');
require('@iopipe/profiler');
require('@iopipe/logger');
const iopipe = require('@iopipe/iopipe')({"plugins":["@iopipe/trace","@iopipe/profiler","@iopipe/logger"]});

exports['expireSwitchAlerts'] = function attemptExpireSwitchAlerts(event, context, callback) {
  try {
    return iopipe((evt, ctx, cb) => {
      return require('../src/alerts').expireOld(evt, ctx, cb);
    })(event, context, callback);
  } catch (err) {
    throw err;
  }
};
``` 

so that's promising, I do have an env variable `IOPIPE_LOGGER_ENABLED` set to `true` on the lambda, but still no logs inside iopipe, all I do in the lambda is a console.log('Running'). 

Let me know if I've missed some other config. 

Another feedback: it's not clear how to set iopipe plugins on the package.json or on the .iopiperc, if I go for the syntax in the .rc file 

```
{
  "token": "wow_token",
  "plugins": [
    "@iopipe/trace",
    ["@iopipe/profiler", {"enabled": true}]
  ]
}
```
I get this stack trace at runtime: 

```

    "errorMessage": "Cannot find module '@iopipe/trace,[object Object]'",
    "errorType": "Error",
    "stackTrace": [
        "Function.Module._load (module.js:474:25)",
        "Module.require (module.js:596:17)",
        "require (internal/module.js:11:18)",
        "Object.<anonymous> (/var/task/iopipe_handlers/expireSwitchAlerts-0-iopipe.js:1:63)",
        "Module._compile (module.js:652:30)",
        "Object.Module._extensions..js (module.js:663:10)",
        "Module.load (module.js:565:32)",
        "tryModuleLoad (module.js:505:12)",
        "Function.Module._load (module.js:497:3)"
    ]
}
```

**Comment by pselle** [comment]
@aterreno We've made a new release that should resolve this issue for you! Can you try version 1.1.1 of the plugin and let us know if you still have issues?

**Comment by kolanos** [comment]
@aterreno Also, for the `package.json` configuration, it's a little different from the rc file, see the "package.json Configuration" section here for an example:
https://github.com/iopipe/iopipe-js-core/blob/master/README.md

**Comment by aterreno** [comment]
Thanks @pselle, I now see a 'Logger' Label inside the IOPipe console on the invocation of the lambda, however still no luck with seeing logs. 

The lambda is a cron lambda (if that matters at all), there's a console.log immediately on execution on the handler. 

At runtime I have:
```process.env.IOPIPE_LOGGER_ENABLED: true```
in the context obj I have:
```
    "iopipe": {
        "version": "1.14.2",
        "config": {},
        "mark": {}
    }
``` 

the rc file is: 

```
{
    "token": "SECRET",
    "plugins": [
      "@iopipe/trace",
      "@iopipe/profiler",
      "@iopipe/logger"
    ]
}
```
dependencies are:

```
    "@iopipe/core": "1.13.0",
    "@iopipe/iopipe": "1.9.0",
    "@iopipe/logger": "1.1.1",
    "@iopipe/profiler": "2.0.3",
    "@iopipe/trace": "1.2.1",
``` 

@kolanos I don't spot any difference between rc file and package.json tbh on the readme, the only difference is that in the package the config is wrapped inside iopipe while on the rc file it's just the inside bit. 

White writing I noticed that iopipe is at the latest at runtime, it must be the plugin upgrading automatically. Could that be the problem or the logger is now supposed to work with any version of iopipe/core? 

Also, we are on a free plan, as far as I understand this works also on the free plan. 

thanks again

**Comment by adjohn** [comment]
Fixed in https://github.com/iopipe/iopipe-js-logger/pull/19

**Comment by aterreno** [comment]
@adjohn why would you say it's fixed if I still can't see the logs, can you pls explain what I misconfigured? thx

**Comment by adjohn** [comment]
@aterreno several users have reported this as fixed after the update to v1.1.1.  If that's not the case for you do you mind hopping in our support Slack to work with our engineers to identify the issue? https://iopipe.now.sh
